variables:
- template: ./Variables/common.yml
  
trigger:
- master
stages:
- stage: CI_Build
  jobs:
  - job: Build
    pool: 
      name: ${{ variables.PoolName}}
      vmImage: ${{ variables.vmImage}}
     
    steps:
    - template: ./build.yml
      parameters:
        AppserviceArtifact: 'UserManangement.API'