parameters:
  - name: AppserviceArtifact

steps:
- task: UseDotNet@2
  displayName: Use .NET Core sdk
  inputs:
    packageType: sdk
    version: 3.1.101
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'
    feedsToUse: 'select'
        
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '-c $(Build.Configuration)'

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
    projects: '**/*.Tests.csproj'
    arguments: '-c $(Build.Configuration)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.csproj'
    modifyOutputPath: false
    arguments: '-c $(Build.Configuration) -o $(Build.ArtifactStagingDirectory)/app/${{ parameters.AppserviceArtifact }}'
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: ${{ parameters.AppserviceArtifact }}