name: .NET Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      continue-on-error: false
      run: dotnet build --configuration Release
      working-directory: UserManagementApp/

    - name: Test with dotnet
      continue-on-error: false
      run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
      working-directory: UserManagementApp/
        
    - name: Publish
      continue-on-error: false
      run: dotnet publish -c Release -o ./Artifacts
      working-directory: UserManagementApp/
      
    - name: Upload Artifact
      continue-on-error: false
      uses: actions/upload-artifact@v1.0.0
      with: 
        name: UserManagementApp
        path: UserManagementApp/Artifacts
