name: .NET Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      continue-on-error: false
      run: dotnet build --configuration Release
      working-directory: UserManagementApp/

    - name: Test with dotnet
      continue-on-error: false
      run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
      working-directory: UserManagementApp/
      
    - name: Copy Coverage To Predictable Location
      run: cp coverage/**/coverage.cobertura.xml coverage.cobertura.xml
      working-directory: UserManagementApp/
      
    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.2.0
      with:
        filename:  /home/runner/work/UserManagementApp/UserManagementApp/UserManagementApp/coverage/*/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
    
    - name: Publish
      continue-on-error: false
      run: dotnet publish -c Release -o ./Artifacts
      working-directory: UserManagementApp/
      
    - name: Upload Artifact
      continue-on-error: false
      uses: actions/upload-artifact@v1.0.0
      with: 
        name: UserManagementApp
        path: UserManagementApp/Artifacts
